coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        enabled: false
      main:
        target: 80%
        threshold: 1%
        base: parent
    patch:
      default:
        enabled: false
      main:
        target: 80%
        threshold: 1%

ignore:
  - "**/*test*/**"
  - "**/*test*.*"
  - "*test*"
  - "examples/**"
  - "internal/test/**"
  - "**/suite.go"

